language: php
php:
#  - '5.5'
  - '5.6'

sudo: false
before_script:
  - composer require "symfony/symfony:${SYMFONY_VERSION}"
env:
#  - SYMFONY_VERSION=2.3.*
#  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.*
cache:
  files:
    - composer.lock
  directories:
    - $HOME/.composer
    - vendor

