language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'

sudo: false

matrix:
  fast_finish: true

install:
  - composer require "symfony/symfony:${SYMFONY_VERSION}"

script:
  - composer run-script test

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.*

cache:
  files:
    - composer.lock
  directories:
    - $HOME/.composer
    - vendor
