language: php
php:
  - '5.5'
  - '5.6'

sudo: false
before_script:
  - composer require --update-with-dependencies "symfony/symfony:${SYMFONY_VERSION}"
env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.*
cache:
  files:
    - composer.lock
  directories:
    - $HOME/.composer
    - vendor

