language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'

sudo: false

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.*

matrix:
  fast_finish: true

install:
  - composer global require hirak/prestissimo
  - composer require "symfony/symfony:${SYMFONY_VERSION}" --update-with-dependencies
  - composer build-ci

script:
  - composer test

cache:
  directories:
    - $HOME/.composer
