<?php
/******** WARNING : THIS FILE IS JUST A TEMPLATE, IT IS NOT LOADABLE AS IS ********/
namespace {

    /**
     * Autogenerated by Behat3SymfonyExtension.
     * Don't touch the content it will be erased !
     * See Yoanm\Behat3SymfonyExtension\Factory\KernelFactory::load()
     *
     * This file should be automatically deleted after kernel load. Except if kernel.kernelDebug === true
     */
    use __OriginalKernelClassNameToReplace__ as YoanmBehat3SymfonyKernelBridgeBaseKernel;
    use Yoanm\Behat3SymfonyExtension\Dispatcher\BehatKernelEventDispatcher;

    class YoanmBehat3SymfonyKernelBridge__BridgeId__ extends YoanmBehat3SymfonyKernelBridgeBaseKernel
    {
        /** @var BehatKernelEventDispatcher */
        private $behatKernelEventDispatcher;

        /**
         * @param BehatKernelEventDispatcher $behatKernelEventDispatcher
         */
        public function setBehatKernelEventDispatcher(BehatKernelEventDispatcher $behatKernelEventDispatcher)
        {
            $this->behatKernelEventDispatcher = $behatKernelEventDispatcher;
        }

        /**
         * Will dispatch events related to kernel boot action
         * Rely on parent class method
         *
         * {@inheritdoc}
         */
        public function boot()
        {
            $this->behatKernelEventDispatcher->beforeBoot($this);
            parent::boot();
            $this->behatKernelEventDispatcher->afterBoot($this);
        }

        /**
         * Will dispatch events related to kernel shutdown action
         * Rely on parent class method
         *
         * {@inheritdoc}
         */
        public function shutdown()
        {
            $this->behatKernelEventDispatcher->beforeShutdown($this);
            parent::shutdown();
            $this->behatKernelEventDispatcher->afterShutdown($this);
        }
    }
}
